/*******************************************************************************
* (c) Copyright 2011 Actel Corporation.  All rights reserved.
*
*  This is a file generated by the IAR Workbench software project
*  It can be modified by the user and will not be overwritten when
*  the software IDE is run after the first time.
*/

/*-------------------------------------------------------------------------*/
/**
 * main() function.
 */
int main()
{

/*---------------------------------------------------------------
    Initialization and Setup
----------------------------------------------------------------*/
    
/*---------------------------------------------------------------
* Infinite loop.
----------------------------------------------------------------*/
    for(;;)
    {
    }
}
